'use client';

import { useState, useTransition } from 'react';

import { dismissWalletHandoff } from '../actions';

interface WalletPayload {
  accountId: string;
  publicKey: string;
  privateKey: string;
  evmAddress: string;
  createTransactionId: string;
  initialBalanceTinybars: number;
  createdAt: string;
}

/**
 * Client-side reveal/download UX for the one-time wallet payload. The
 * private key is hidden behind a "Reveal" toggle so the user does not
 * shoulder-surf it accidentally, and a "Download JSON" button packages
 * everything as a file the user can drop into a password manager.
 * "I&rsquo;ve saved them" clears the server cookie and bounces to /dashboard.
 */
export function WalletReveal({ payload }: { payload: WalletPayload }) {
  const [revealed, setRevealed] = useState(false);
  const [pending, startTransition] = useTransition();

  const handleDownload = () => {
    // JSON file the user can stash in a password manager. We
    // intentionally exclude any platform-internal fields (like the
    // create transaction id is informational only) — the file is
    // shaped to be re-importable into Hedera wallets that accept
    // raw DER keys.
    const file = {
      accountId: payload.accountId,
      publicKey: payload.publicKey,
      privateKey: payload.privateKey,
      evmAddress: payload.evmAddress,
      network: 'hedera',
      createdAt: payload.createdAt,
      note: 'Generated by Shamba Traceability at onboarding. Keep the privateKey field secret — it controls this Hedera account.',
    };
    const blob = new Blob([JSON.stringify(file, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `shamba-hedera-wallet-${payload.accountId.replace(/\./g, '-')}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleContinue = () => {
    startTransition(async () => {
      await dismissWalletHandoff();
    });
  };

  return (
    <div className="mt-6 space-y-5 rounded-md border border-soil-200 bg-white p-6">
      <Field label="Hedera account id">
        <code className="block break-all rounded-md bg-soil-50 px-3 py-2 font-mono text-sm text-soil-900">
          {payload.accountId}
        </code>
      </Field>

      <Field label="EVM address (for Ethereum tooling)">
        <code className="block break-all rounded-md bg-soil-50 px-3 py-2 font-mono text-xs text-soil-700">
          {payload.evmAddress}
        </code>
      </Field>

      <Field label="Public key (DER)">
        <code className="block break-all rounded-md bg-soil-50 px-3 py-2 font-mono text-xs text-soil-700">
          {payload.publicKey}
        </code>
      </Field>

      <Field label="Private key (DER) — SECRET">
        {revealed ? (
          <code className="block break-all rounded-md bg-red-50 px-3 py-2 font-mono text-xs text-red-900">
            {payload.privateKey}
          </code>
        ) : (
          <button
            type="button"
            onClick={() => setRevealed(true)}
            className="inline-flex h-9 items-center justify-center rounded-md border border-soil-300 bg-soil-50 px-4 text-xs font-medium text-soil-800 transition-colors hover:bg-soil-100"
          >
            Reveal private key
          </button>
        )}
      </Field>

      <div className="flex flex-col gap-3 pt-2 sm:flex-row">
        <button
          type="button"
          onClick={handleDownload}
          className="inline-flex h-11 items-center justify-center rounded-md bg-leaf-600 px-6 text-sm font-medium text-white shadow-sm transition-colors hover:bg-leaf-700"
        >
          Download keys (JSON)
        </button>
        <button
          type="button"
          onClick={handleContinue}
          disabled={pending}
          aria-busy={pending}
          className="inline-flex h-11 items-center justify-center rounded-md border border-soil-300 bg-white px-6 text-sm font-medium text-soil-800 transition-colors hover:bg-soil-50 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {pending ? 'Finishing...' : "I've saved them — continue"}
        </button>
      </div>

      <p className="pt-2 text-xs text-soil-600">
        Funded with {(payload.initialBalanceTinybars / 100_000_000).toFixed(2)} HBAR. Create tx:{' '}
        <code className="font-mono">{payload.createTransactionId}</code>
      </p>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <span className="text-xs font-medium uppercase tracking-wide text-soil-700">{label}</span>
      <div className="mt-1">{children}</div>
    </div>
  );
}
