// Package hedera wraps the Hedera SDK with the operations the publisher needs.
//
// The current implementation is a mock: it returns deterministic-looking IDs
// and transaction hashes without performing any network calls. A real SDK
// adapter will replace this in a follow-up PR; the public interface here is
// shaped to absorb that change without churn at the call sites.
package hedera

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"log/slog"
	"strconv"
	"sync/atomic"
	"time"

	"github.com/Shamba-Records-Limited/traceability/services/hedera-publisher/internal/config"
)

// Client is the operations surface the publisher exposes against Hedera.
type Client interface {
	// Mode returns "real" or "mock".
	Mode() string

	// SubmitMessage writes a single message to an HCS topic. If topicID is
	// empty, a new topic is created.
	SubmitMessage(ctx context.Context, topicID string, payload []byte) (SubmitMessageResult, error)

	// MintNFT mints a single NFT with `metadata` under the given collection token.
	// If tokenID is empty, a new collection is created with the supplied symbol/name.
	MintNFT(ctx context.Context, tokenID, name, symbol string, metadata []byte) (MintNFTResult, error)

	// TransferNFT transfers ownership of a serial-numbered NFT from sender to receiver.
	TransferNFT(ctx context.Context, tokenID string, serial int64, fromAccount, toAccount string) (TxResult, error)

	// ExecuteContract invokes `functionSelector` on the supplied Hedera contract,
	// passing the already-ABI-encoded `args` bytes. Returns the transaction id
	// + consensus timestamp; the deployed contract's emitted events are read
	// off the mirror node by the integrating client (we don't surface them
	// here because gas-cost-of-record varies per contract and the publisher
	// stays single-shot).
	//
	// `contractID` accepts Hedera's `0.0.<num>` form OR a 0x-prefixed EVM
	// address; the implementation translates as needed.
	ExecuteContract(ctx context.Context, contractID, functionSelector string, args []byte, gasLimit int64) (ContractCallResult, error)

	// CreateAccount provisions a fresh Hedera account from the operator
	// account. An ECDSA secp256k1 keypair is generated by the publisher;
	// the new account is funded with `initialBalanceTinybars` HBAR from
	// the operator and uses the generated public key as both its account
	// key AND its EVM-alias source (so the account is reachable both via
	// `0.0.<num>` and via its derived EVM address).
	//
	// The returned `PrivateKey` is the only copy that will ever leave the
	// service — the publisher does not persist generated keys. Callers
	// are expected to encrypt-at-rest immediately and surface the
	// cleartext to the end user exactly once.
	CreateAccount(ctx context.Context, initialBalanceTinybars int64, memo string) (CreateAccountResult, error)

	// Close releases any held resources.
	Close() error
}

// SubmitMessageResult captures the protocol-level outcome of an HCS submission.
type SubmitMessageResult struct {
	TopicID            string `json:"topicId"`
	SequenceNumber     int64  `json:"sequenceNumber"`
	ConsensusTimestamp string `json:"consensusTimestamp"`
	TransactionID      string `json:"transactionId"`
}

// MintNFTResult captures the outcome of a mint operation.
type MintNFTResult struct {
	TokenID       string `json:"tokenId"`
	SerialNumber  int64  `json:"serialNumber"`
	TransactionID string `json:"transactionId"`
}

// TxResult is the minimal result returned by simple transactions.
type TxResult struct {
	TransactionID      string `json:"transactionId"`
	ConsensusTimestamp string `json:"consensusTimestamp"`
}

// ContractCallResult is returned by ExecuteContract. `GasUsed` is informational
// and reflects the network's reported gas consumption; the publisher does not
// charge it back to the caller because the operator account pays.
type ContractCallResult struct {
	ContractID         string `json:"contractId"`
	TransactionID      string `json:"transactionId"`
	ConsensusTimestamp string `json:"consensusTimestamp"`
	GasUsed            int64  `json:"gasUsed"`
}

// CreateAccountResult is returned by CreateAccount. It carries the only
// copy of the generated private key that will ever leave the service —
// the publisher does not persist it. `EvmAddress` is the 0x-prefixed
// 20-byte address derived from the ECDSA public key (Hedera computes the
// same address client-side when the account is created with an EVM alias).
//
// `InitialBalanceTinybars` is echoed back from the request so the caller
// can distinguish a default-funded create from an explicit override; it
// is not read from the receipt because the SDK does not round-trip it.
type CreateAccountResult struct {
	AccountID              string `json:"accountId"`
	PublicKey              string `json:"publicKey"`
	PrivateKey             string `json:"privateKey"`
	EvmAddress             string `json:"evmAddress"`
	CreateTransactionID    string `json:"createTransactionId"`
	InitialBalanceTinybars int64  `json:"initialBalance"`
}

// NewClient returns the appropriate client implementation based on configuration.
// In mock mode the returned client never contacts the network.
func NewClient(cfg *config.Config, logger *slog.Logger) (Client, error) {
	if cfg.MockMode {
		logger.Warn("hedera client running in mock mode; no real network calls will be made")
		return newMockClient(), nil
	}
	return newSDKClient(cfg, logger)
}

// --- mock client ----------------------------------------------------------

type mockClient struct {
	topicSeq atomic.Int64
	mintSeq  atomic.Int64
	txSeq    atomic.Int64
}

func newMockClient() Client { return &mockClient{} }

func (m *mockClient) Mode() string { return "mock" }

func (m *mockClient) SubmitMessage(_ context.Context, topicID string, payload []byte) (SubmitMessageResult, error) {
	if topicID == "" {
		topicID = "0.0." + strconv.FormatInt(1_000_000+m.topicSeq.Add(1), 10)
	}
	hash := sha256.Sum256(payload)
	return SubmitMessageResult{
		TopicID:            topicID,
		SequenceNumber:     m.topicSeq.Add(1),
		ConsensusTimestamp: time.Now().UTC().Format(time.RFC3339Nano),
		TransactionID:      "mock-tx-" + hex.EncodeToString(hash[:8]),
	}, nil
}

func (m *mockClient) MintNFT(_ context.Context, tokenID, _, _ string, metadata []byte) (MintNFTResult, error) {
	if tokenID == "" {
		tokenID = "0.0." + strconv.FormatInt(2_000_000+m.mintSeq.Add(1), 10)
	}
	hash := sha256.Sum256(metadata)
	return MintNFTResult{
		TokenID:       tokenID,
		SerialNumber:  m.mintSeq.Add(1),
		TransactionID: "mock-tx-" + hex.EncodeToString(hash[:8]),
	}, nil
}

func (m *mockClient) TransferNFT(_ context.Context, _ string, _ int64, _, _ string) (TxResult, error) {
	id := "mock-tx-" + strconv.FormatInt(m.txSeq.Add(1), 10)
	return TxResult{
		TransactionID:      id,
		ConsensusTimestamp: time.Now().UTC().Format(time.RFC3339Nano),
	}, nil
}

func (m *mockClient) ExecuteContract(_ context.Context, contractID, _ string, args []byte, _ int64) (ContractCallResult, error) {
	hash := sha256.Sum256(args)
	if contractID == "" {
		// Mirror the real SDK's behaviour: an explicit contract id is required.
		// Returning an error keeps mock + real parity instead of papering over
		// the misuse with a synthetic id.
		return ContractCallResult{}, fmt.Errorf("contractID is required")
	}
	return ContractCallResult{
		ContractID:         contractID,
		TransactionID:      "mock-tx-" + hex.EncodeToString(hash[:8]),
		ConsensusTimestamp: time.Now().UTC().Format(time.RFC3339Nano),
		GasUsed:            50_000,
	}, nil
}

// CreateAccount in mock mode returns deterministic-looking material without
// touching the network. The returned `PrivateKey` is NOT a valid ECDSA key
// — the prefix advertises that it is mock material so any caller that
// accidentally tries to load it into the SDK fails fast. Tests that need
// to exercise the encrypt-at-rest path treat the bytes as opaque.
func (m *mockClient) CreateAccount(_ context.Context, initialBalanceTinybars int64, _ string) (CreateAccountResult, error) {
	id := "0.0." + strconv.FormatInt(3_000_000+m.txSeq.Add(1), 10)
	salt := sha256.Sum256([]byte(id))
	return CreateAccountResult{
		AccountID:              id,
		PublicKey:              "mock-public-" + hex.EncodeToString(salt[:8]),
		PrivateKey:             "mock-private-" + hex.EncodeToString(salt[8:16]),
		EvmAddress:             "0x" + hex.EncodeToString(salt[:20]),
		CreateTransactionID:    "mock-tx-" + hex.EncodeToString(salt[:8]),
		InitialBalanceTinybars: initialBalanceTinybars,
	}, nil
}

func (m *mockClient) Close() error { return nil }
